 $(function(){
        var owl = $('#test');
        $('#test').owlCarousel({
            loop:true,
              autoplay:true,
        autoplayTimeout:5000,
        responsiveClass:true,
        margin:0,
        autoplayHoverPause:true,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:4
                    }
                }
            });
        $('.play').on('click',function(){
            owl.trigger('play.owl.autoplay',[5000])
        })
        $('.stop').on('click',function(){
            owl.trigger('stop.owl.autoplay')
        })
    });